// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/pvz.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListPVZRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPVZRequest) Reset() {
	*x = ListPVZRequest{}
	mi := &file_proto_pvz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPVZRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPVZRequest) ProtoMessage() {}

func (x *ListPVZRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pvz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPVZRequest.ProtoReflect.Descriptor instead.
func (*ListPVZRequest) Descriptor() ([]byte, []int) {
	return file_proto_pvz_proto_rawDescGZIP(), []int{0}
}

type PVZ struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RegistrationDate string                 `protobuf:"bytes,2,opt,name=registration_date,json=registrationDate,proto3" json:"registration_date,omitempty"`
	City             string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PVZ) Reset() {
	*x = PVZ{}
	mi := &file_proto_pvz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PVZ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVZ) ProtoMessage() {}

func (x *PVZ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pvz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVZ.ProtoReflect.Descriptor instead.
func (*PVZ) Descriptor() ([]byte, []int) {
	return file_proto_pvz_proto_rawDescGZIP(), []int{1}
}

func (x *PVZ) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PVZ) GetRegistrationDate() string {
	if x != nil {
		return x.RegistrationDate
	}
	return ""
}

func (x *PVZ) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type ListPVZResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PVZ                 `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPVZResponse) Reset() {
	*x = ListPVZResponse{}
	mi := &file_proto_pvz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPVZResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPVZResponse) ProtoMessage() {}

func (x *ListPVZResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pvz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPVZResponse.ProtoReflect.Descriptor instead.
func (*ListPVZResponse) Descriptor() ([]byte, []int) {
	return file_proto_pvz_proto_rawDescGZIP(), []int{2}
}

func (x *ListPVZResponse) GetItems() []*PVZ {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_pvz_proto protoreflect.FileDescriptor

const file_proto_pvz_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/pvz.proto\x12\x03pvz\"\x10\n" +
	"\x0eListPVZRequest\"V\n" +
	"\x03PVZ\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x11registration_date\x18\x02 \x01(\tR\x10registrationDate\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\"1\n" +
	"\x0fListPVZResponse\x12\x1e\n" +
	"\x05items\x18\x01 \x03(\v2\b.pvz.PVZR\x05items2D\n" +
	"\n" +
	"PVZService\x126\n" +
	"\aListPVZ\x12\x13.pvz.ListPVZRequest\x1a\x14.pvz.ListPVZResponse\"\x00B\x13Z\x11pvz-service/protob\x06proto3"

var (
	file_proto_pvz_proto_rawDescOnce sync.Once
	file_proto_pvz_proto_rawDescData []byte
)

func file_proto_pvz_proto_rawDescGZIP() []byte {
	file_proto_pvz_proto_rawDescOnce.Do(func() {
		file_proto_pvz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pvz_proto_rawDesc), len(file_proto_pvz_proto_rawDesc)))
	})
	return file_proto_pvz_proto_rawDescData
}

var file_proto_pvz_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_pvz_proto_goTypes = []any{
	(*ListPVZRequest)(nil),  // 0: pvz.ListPVZRequest
	(*PVZ)(nil),             // 1: pvz.PVZ
	(*ListPVZResponse)(nil), // 2: pvz.ListPVZResponse
}
var file_proto_pvz_proto_depIdxs = []int32{
	1, // 0: pvz.ListPVZResponse.items:type_name -> pvz.PVZ
	0, // 1: pvz.PVZService.ListPVZ:input_type -> pvz.ListPVZRequest
	2, // 2: pvz.PVZService.ListPVZ:output_type -> pvz.ListPVZResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_pvz_proto_init() }
func file_proto_pvz_proto_init() {
	if File_proto_pvz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pvz_proto_rawDesc), len(file_proto_pvz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pvz_proto_goTypes,
		DependencyIndexes: file_proto_pvz_proto_depIdxs,
		MessageInfos:      file_proto_pvz_proto_msgTypes,
	}.Build()
	File_proto_pvz_proto = out.File
	file_proto_pvz_proto_goTypes = nil
	file_proto_pvz_proto_depIdxs = nil
}
